POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "testtest1@test.com",
    "password": "@Testtest",
    "confirmPassword": "@Testtest"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "testtest1@test.com",
    "password": "@Testtest"
}

###
DELETE http://localhost:3000/auth/logout
###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    
}

